### PR TITLE
Drop exhibitor

### PR DESCRIPTION
**Pull request by eherot**

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@eherot you finally got rid of Exhibitor! Awesome.

**Comment by eherot** [comment]
Well I want to but the exact procedure for converting an exhibitor-managed cluster to a non-exhibitor managed cluster I am still trying to figure out.

**Comment by jeffbyrnes** [comment]
Not sure how far you’ve gotten, but off the top of my head, some steps:

1. Disable Exhibitors auto-restart stuff (might already be off)
2. Check what’s in the S3-stored `zoo.cfg` that Exhibitor uses, and make sure the cookbook sets the same values
3. Spin up new ZK nodes, manually adding them to the Exhibitor-managed ones’ config
    * These nodes should pick up the existing Exhibitor-managed nodes through some sort of search, so they set their config properly right from the get-go

I _think_ that should get you straightened out.

By the way, what prompted this?

**Comment by eherot** [comment]
#'s 2 and 3 are a bit easier said than done without writing a whole bunch of cookbook logic that's completely specific to the migration, because the existing old ZK cookbook had no concept of the servers belonging to any kind of cluster.

I'm probably just going to end up manually editing the config file a whole lot.

**Comment by jeffbyrnes** [comment]
@eherot that’s what I’d end up doing, as well, if it were me. It’s a one-time migration, so no sense in codifying it.

**Pull request merged**
